title: WCRS FM
description: Streaming community radio.
url: "https://wcrsfm.org"
baseurl: ""

markdown: kramdown
plugins: []

collections:
  articles:
    output: true
    permalink: /news/:path/
  programs:
    output: true
    permalink: /programs/:path/


include:
  - .htaccess

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .ddev
  - README.md
  - node_modules
  - mail_config.php
  - composer.json
  - composer.lock
  - data
